import os
import sys
import json
import logging
from datetime import datetime, timedelta

# Add current directory to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from trend_engine.db import db
from trend_engine.email.send_sendgrid import send_email_report
from google import genai
from trend_engine.config import GEMINI_API_KEY

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def generate_weekly_report():
    """
    Generates a weekly HTML report of the top global viral trends.
    """
    logger.info("📅 Generating Weekly Global Virality Report...")
    
    if not db.client:
        logger.error("❌ Database not connected")
        return

    # 1. Fetch Top Trends (Last 7 Days)
    seven_days_ago = (datetime.now() - timedelta(days=7)).isoformat()
    
    try:
        # Get top 10 recent videos
        result = db.client.table("global_viral_trends")\
            .select("*")\
            .gte("created_at", seven_days_ago)\
            .order("views", desc=True)\
            .limit(10)\
            .execute()
            
        trends = result.data
        
        if not trends:
            logger.warning("⚠️ No trends found for this week.")
            return

        logger.info(f"📊 Found {len(trends)} viral trends to summarize.")

        # 2. Summarize with AI (The DOSSIER)
        # We want to identify common patterns across these videos
        
        # Prepare context for AI
        trends_context = []
        for t in trends:
            analysis = t.get('analysis_json', {})
            if isinstance(analysis, str):
                analysis = json.loads(analysis)
                
            trends_context.append({
                "title": t.get('title'),
                "url": t.get('url'),
                "views": t.get('views'),
                "hook": analysis.get('hook', {}),
                "audio": analysis.get('audio', {}),
                "pacing": analysis.get('pacing', {}),
                "replica_potential": analysis.get('replica_potential', 0)
            })
            
        trends_json = json.dumps(trends_context, indent=2)
        
        # Generate Report Content using Gemini
        client = genai.Client(api_key=GEMINI_API_KEY)
        
        prompt = f"""
        You are the Chief Viral Officer. Write the "Global Virality Dossier" for this week based on these top performing videos.
        
        DATA:
        {trends_json}
        
        OUTPUT FORMAT: HTML (Ready for email). Use inline CSS.
        structure:
        1. **header**: "The Viral Dossier 📁"
        2. **The Meta-Trend**: What is the ONE big pattern this week? (e.g. "Everyone is using silence in the first 2s").
        3. **Top 3 Viral Deconstructions**:
           - Video Title (Link)
           - ⚡ The Hook: Why it worked (from analysis)
           - 🎵 Audio Strategy
           - 📋 Replicate This: 1-sentence instruction.
        4. **Audio Bank**: List the top 3 audio vibes/types to use.
        5. **3 Hook Scripts**: Write 3 fill-in-the-blank hook scripts based on these winners.
        
        Tone: Professional, Insightful, Actionable. No fluff.
        """
        
        response = client.models.generate_content(
            model="gemini-2.0-flash-exp",
            contents=prompt
        )
        
        html_content = response.text
        
        # Wrap in standard template container if needed, or just use raw output if good
        # Let's verify it has <html> tag, or wrap it
        if "<html>" not in html_content.lower():
            html_content = f"""
            <!DOCTYPE html>
            <html>
            <body style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
                {html_content}
                <div style="margin-top: 40px; font-size: 12px; color: #888; text-align: center;">
                    Generated by Global Virality Researcher 🤖
                </div>
            </body>
            </html>
            """
            
        # 3. Send Email
        subject = f"📁 The Viral Dossier - Week {datetime.now().isocalendar()[1]}"
        if send_email_report(html_content, subject=subject):
            logger.info("✅ Weekly report sent successfully!")
        else:
            logger.error("❌ Failed to send weekly report.")

    except Exception as e:
        logger.error(f"❌ Error generating weekly report: {e}")

if __name__ == "__main__":
    generate_weekly_report()
